name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup ENV
      run: |
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "@inlet-media:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> .npmrc

        echo "registry=https://registry.npmjs.org/" >> .yarnrc
        echo "@inlet-media:registry=https://npm.pkg.github.com/" >> .yarnrc

    - name: Build
      run: |
        yarn
        yarn build
